import { existsSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { isSafeIdForPath } from "./trackid";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { dataDir } from "./env";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { ytdlpPath } from "./env";
import { localePref } from "./settings";
import { cookieArgs } from "./streams";
import { searchableTitle } from "./metadata";

const execFileAsync = promisify(execFile);

export type LyricLine = { t: number; text: string };
export type Lyrics = {
  lines: LyricLine[];   // empty when the source only had unsynced text
  plain: string;
  source: "lrclib" | "captions" | "auto-captions";
  autoGenerated: boolean;
};

/** `[mm:ss.xx] text`, and a line may carry several stamps for a repeated hook. */
export function parseLrc(lrc: string): LyricLine[] {
  const out: LyricLine[] = [];
  for (const raw of (lrc || "").split(/\r?\n/)) {
    const stamps = [...raw.matchAll(/\[(\d+):(\d+(?:[.:]\d+)?)\]/g)];
    if (!stamps.length) continue;
    const text = raw.replace(/\[[^\]]*\]/g, "").trim();
    for (const m of stamps) {
      const t = Number(m[1]) * 60 + Number(String(m[2]).replace(":", "."));
      if (Number.isFinite(t)) out.push({ t, text });
    }
  }
  return out.sort((a, b) => a.t - b.t);
}

/** YouTube's json3 caption payload: one event per cue, text split into segs. */
export function parseJson3(payload: any): LyricLine[] {
  const out: LyricLine[] = [];
  for (const e of payload?.events ?? []) {
    if (typeof e?.tStartMs !== "number") continue;
    const text = (e.segs ?? []).map((s: any) => s?.utf8 ?? "").join("").replace(/\s+/g, " ").trim();
    if (!text || text === "\n") continue;
    out.push({ t: e.tStartMs / 1000, text });
  }
  return out.sort((a, b) => a.t - b.t);
}

async function fromLrclib(
  artist: string, title: string, album: string, duration: number,
): Promise<Lyrics | null> {
  const q = new URLSearchParams({ artist_name: artist, track_name: title });
  if (album) q.set("album_name", album);
  if (duration > 0) q.set("duration", String(Math.round(duration)));
  // /get wants an exact match; /search is the fallback for a near miss
  for (const url of [`https://lrclib.net/api/get?${q}`,
                     `https://lrclib.net/api/search?${new URLSearchParams({ artist_name: artist, track_name: title })}`]) {
    try {
      const res = await fetch(url, { headers: { "User-Agent": "melo (https://github.com/melo-foundation/melo)" } });
      if (!res.ok) continue;
      const body: any = await res.json();
      const hit = Array.isArray(body) ? body[0] : body;
      if (!hit) continue;
      // a search hit is only a guess: hold it to the duration we are playing
      if (Array.isArray(body) && duration > 0 && Math.abs((hit.duration ?? 0) - duration) > 5) continue;
      const lines = parseLrc(hit.syncedLyrics ?? "");
      const plain = (hit.plainLyrics ?? "").trim();
      if (!lines.length && !plain) continue;
      return { lines, plain, source: "lrclib", autoGenerated: false };
    } catch { /* try the next one */ }
  }
  return null;
}

async function fromCaptions(videoId: string, allowAuto: boolean): Promise<Lyrics | null> {
  // The timedtext URL returns Google's block page to plain requests, so yt-dlp
  // downloads the track with its session and cookies. Written subtitles first;
  // auto ones only when asked for, and they arrive labelled.
  const { hl } = localePref();
  const lang = (hl || "en").split("-")[0];
  const dir = mkdtempSync(join(tmpdir(), "melo-subs-"));
  const langs = lang === "en" ? "en.*" : `${lang}.*,en.*`;
  try {
    for (const auto of allowAuto ? [false, true] : [false]) {
      try {
        await execFileAsync(
          ytdlpPath(),
          [...(await cookieArgs()), "--no-warnings", "--skip-download", "--no-playlist",
           auto ? "--write-auto-subs" : "--write-subs",
           "--sub-langs", langs, "--sub-format", "json3",
           // YouTube answers caption downloads with 429 readily, and the
           // default ten retries with backoff outlast any sane wait. One try:
           // a miss is cached, and the pane says so instead of spinning.
           "--retries", "1", "--extractor-retries", "1", "--socket-timeout", "10",
           "-o", join(dir, "%(id)s.%(ext)s"),
           `https://www.youtube.com/watch?v=${videoId}`],
          { timeout: 25000, windowsHide: true },
        );
      } catch { /* 429 and "no subtitles" land here alike; try the next kind */ }
      const file = readdirSync(dir).find((f) => f.endsWith(".json3"));
      if (!file) continue;
      const lines = parseJson3(JSON.parse(readFileSync(join(dir, file), "utf8")));
      rmSync(join(dir, file), { force: true });
      if (!lines.length) continue;
      return {
        lines,
        plain: lines.map((l) => l.text).join("\n"),
        source: auto ? "auto-captions" : "captions",
        autoGenerated: auto,
      };
    }
    return null;
  } finally {
    try { rmSync(dir, { recursive: true, force: true }); } catch { /* best effort */ }
  }
}

const MISS_TTL_MS = 7 * 24 * 3600 * 1000;

function cachePath(videoId: string) {
  // Same rule as the thumbnail cache: this id becomes a filename, and an id
  // of `../settings.v2` would write the lyrics cache over the user's settings.
  if (!isSafeIdForPath(videoId)) return null;
  return join(dataDir(), "lyrics", `${videoId}.json`);
}

export async function getLyrics(opts: {
  videoId: string; artist?: string; title?: string; album?: string;
  duration?: number; allowAuto?: boolean;
}): Promise<Lyrics | null> {
  const { videoId } = opts;
  if (!videoId) return null;
  // null when the id could not safely be a filename: the lookup still runs,
  // only the on-disk cache is skipped.
  const p = cachePath(videoId);
  try {
    if (p && existsSync(p)) {
      const c = JSON.parse(readFileSync(p, "utf8"));
      // a miss is cached too, or every play of an unknown track refetches;
      // it expires so a later LRCLIB submission is picked up
      if (c.lyrics) return c.lyrics;
      if (c.allowAuto === (opts.allowAuto === true) && Date.now() - (c.at ?? 0) < MISS_TTL_MS) return null;
    }
  } catch { /* unreadable cache is a miss */ }

  const artist = (opts.artist ?? "").trim();
  const title = (opts.title ?? "").trim();
  let found: Lyrics | null = null;
  // the same rule the metadata chain uses: nothing searchable, no lookup
  if (searchableTitle(title) && artist) {
    found = await fromLrclib(artist, title, (opts.album ?? "").trim(), opts.duration ?? 0);
  }
  if (!found) found = await fromCaptions(videoId, opts.allowAuto === true);

  try {
    if (p) {
      mkdirSync(join(dataDir(), "lyrics"), { recursive: true });
      writeFileSync(p, JSON.stringify({ at: Date.now(), allowAuto: opts.allowAuto === true, lyrics: found }));
    }
  } catch { /* cache is best effort */ }
  return found;
}
